### ISSUE TITLE
Auto Decay / Auto Closing of Portals

### ISSUE THREAD

**Issue by KenObie** [rogermiranda1000/PortalGun#12]
Is there any plan for you to integrate a method that would allow the portals to close automatically after a specific amount of time or upon a specific player event?

**Comment by rogermiranda1000** [comment]
Portal doesn't implement that functionality, so I don't think so. I'm thinking to add some commands/blocks to reset the portal from one player, but you need to use some kind of clock or plugin to combine your mechanic with my code.
