### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by JetString** [rogermiranda1000/PortalGun#15]
https://pastebin.com/VudW9peA

**Comment by JetString** [comment]
the error comes when using skills (or spells if you like) through the portal.
I wonder if there is any way to limit the portals to only player transportation? that would fix this problem.
I know this is not the original idea of a "portal gun". but as an alternative setting it would be lovely.
We use the latest dev build of skillApiPro for that matter.

**Comment by rogermiranda1000** [comment]
Originally I only allow players to move through portals, and then I added entities as an extra feature. So, removing it means that I did that for nothing, but I can add some configuration to enable and disable what can transport a portal and you should be fine.
Right now I'm a little busy, but as soon as I can I add that configuration and I'll check the error log too and try to fix it.

**Comment by rogermiranda1000** [comment]
Teleport entity blacklist was added in https://github.com/rogermiranda1000/PortalGun/commit/795e2a21bb6e1a6a8e1b6bab97e21cdd7d77cd91 and the other bug (related to async move event) should be fixed in 3.0.
