### ISSUE TITLE
Change CustomModelData when shooting portals

### ISSUE THREAD

**Issue by Sebastian11220** [rogermiranda1000/PortalGun#99]
Would it be possible to change the CustomModelData when shooting a portal?

For example if you shoot the orange portal, CustomModelData changes to 1 and when you shoot the green one it changes to 2.
This would allow you to have 2 portal gun models in the resourcepack with orange and green glowing bits and switch between them like in the game.

**Comment by Sebastian11220** [comment]
Missclick, sorry

**Comment by rogermiranda1000** [comment]
> Would it be possible to change the CustomModelData when shooting a portal?

It surely is possible, but I'll need a blue/orange texture for the PortalGun.

**Comment by Sebastian11220** [comment]
I see, You could probably ask the person who made it to modify it or ask for permission to modify it yourself.
There are 5 files you need to recolor and that's pretty much it.
![2023-09-09_22 35 06](https://github.com/rogermiranda1000/PortalGun/assets/48565063/ea9ba4ca-77ac-4a46-a083-b76aea60eb4e)

**Comment by rogermiranda1000** [comment]
@Sebastian11220 did you made the changed? I have the author's permission to use the resourcepack.

**Comment by Sebastian11220** [comment]
Yeah I did

**Comment by rogermiranda1000** [comment]
If you share the modified resourcepack on [my Discord](https://discord.gg/CNzpFrtCFY) I'll appreciate it.

**Comment by rogermiranda1000** [comment]
Implemented in https://github.com/rogermiranda1000/PortalGun/pull/101
